server:
  port: 10010
spring:
  application:
    name: springcloud-zuul

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    springcloud-shopping-items-service: /item/**  #将商品微服务映射到/item/**
    order-service: /trade/**                      #将订单微服务映射到/trade/**
    upload-service: /upload/**
#    upload-service: /**
    user-service: /user/**
    auth-service: /auth/**
  add-host-header: true
  sensitive-headers:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：10000ms
#给token解密的公钥地址和cookie的名称
ly:
  jwt:
    pubKeyPath: D:\IDEA_springcloud_file\rsa\rsa.pub
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/user
      - /api/auth
#      - /api/item
#      - /api/trade
#      - /api/upload